name: Compile PDFs

on: workflow_dispatch

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/latex-action@v2
        with:
          working_directory: writing/
          root_file: |
            main.tex
            si.tex
      - name: Upload Main
        uses: actions/upload-artifact@master
        with:
          name: Main
          path: writing/main.pdf
      - name: Upload si
        uses: actions/upload-artifact@master
        with:
          name: Si
          path: writing/si.pdf
      - name: Upload logs
        uses: actions/upload-artifact@master
        with:
          name: Logs
          path: writing/*.log
        if: always()
